// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzVekcEOjIlbCkZkx75-bPKGZFk0VhwY',
    appId: '1:272681088680:web:c378710d24781bec45b49d',
    messagingSenderId: '272681088680',
    projectId: 'jokko-medapp',
    authDomain: 'jokko-medapp.firebaseapp.com',
    storageBucket: 'jokko-medapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnGxsHEj8GORq5TlxSPGQiCP8uOpK4OYI',
    appId: '1:272681088680:android:9f291df642ab6b4c45b49d',
    messagingSenderId: '272681088680',
    projectId: 'jokko-medapp',
    storageBucket: 'jokko-medapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9QF-OpOrukA56iDdX7OuK--ujb-zz1E',
    appId: '1:272681088680:ios:9ff7c506b0c3a62345b49d',
    messagingSenderId: '272681088680',
    projectId: 'jokko-medapp',
    storageBucket: 'jokko-medapp.firebasestorage.app',
    iosBundleId: 'com.example.jokkodimbali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr9QF-OpOrukA56iDdX7OuK--ujb-zz1E',
    appId: '1:272681088680:ios:9ff7c506b0c3a62345b49d',
    messagingSenderId: '272681088680',
    projectId: 'jokko-medapp',
    storageBucket: 'jokko-medapp.firebasestorage.app',
    iosBundleId: 'com.example.jokkodimbali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFzVekcEOjIlbCkZkx75-bPKGZFk0VhwY',
    appId: '1:272681088680:web:2d3f766007966ca645b49d',
    messagingSenderId: '272681088680',
    projectId: 'jokko-medapp',
    authDomain: 'jokko-medapp.firebaseapp.com',
    storageBucket: 'jokko-medapp.firebasestorage.app',
  );
}
